### ISSUE TITLE
Changes To Evaluation Questions.

### ISSUE THREAD

**Issue by SkaeX** [SkaeX/FCE_Re#4]
The school has decided to change the evaluation questions. This has a few implications on the system. Find the new questions attached.
[MID SEMESTER COURSE EVALUATION QUESTIONS.docx](https://github.com/SkaeX/FCE_Re/files/13282/MID.SEMESTER.COURSE.EVALUATION.QUESTIONS.docx)

**Comment by BrainMaestro** [comment]
Fixed with commit f454f5cc3a3134fb28f4120f2b46abbc5e04f881 on the feature/new-mid-evaluation-questions branch.
